# Generated by Django 5.0.6 on 2024-10-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaTermino',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
