# Generated by Django 5.0.6 on 2024-10-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0002_alter_proyecto_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='prioridad',
            field=models.IntegerField(blank=True),
        ),
    ]
