# Generated by Django 5.0.6 on 2024-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0003_alter_proyecto_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaTermino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
