# Generated by Django 5.0.6 on 2024-10-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0004_alter_proyecto_fechainicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='responsable',
            new_name='apellidom',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechaInicio',
            new_name='fechafallecimiento',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaTermino',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='apellidop',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='maps',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='rut',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
