# Generated by Django 5.0.6 on 2024-10-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0005_rename_responsable_proyecto_apellidom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='apellidom',
            new_name='apellido_m',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='apellidop',
            new_name='apellido_p',
        ),
    ]
