# Generated by Django 4.1.13 on 2024-11-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0006_rename_apellidom_proyecto_apellido_m_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Fallecido',
        ),
    ]
