# Generated by Django 4.1.13 on 2024-11-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0007_rename_proyecto_fallecido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(max_length=100)),
                ('apellido_m', models.CharField(max_length=100)),
                ('fechafallecimiento', models.DateField()),
                ('ubicacion', models.CharField(choices=[('sotano', 'Sótano'), ('bloque_1', 'Bloque 1'), ('bloque_2', 'Bloque 2'), ('miramar', 'Miramar')], max_length=50)),
            ],
        ),
    ]
