# Generated by Django 4.1.13 on 2024-11-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0008_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.AlterField(
            model_name='fallecido',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('sotano', 'Sótano'), ('bloque_1', 'Bloque 1'), ('bloque_2', 'Bloque 2'), ('miramar', 'Miramar')], max_length=50),
        ),
    ]
