# Generated by Django 4.2.7 on 2025-11-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0009_delete_proyecto_alter_fallecido_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallecido',
            name='email_familiar',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Familiar'),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='fecha_mantenimiento_lapida',
            field=models.DateField(blank=True, null=True, verbose_name='Mantto. Lápida (2 años)'),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='fecha_pintura',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura/Retoque (3 años)'),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='fecha_reduccion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Reducción (5 años)'),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='nombre_familiar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Familiar'),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='notificacion_registro_enviada',
            field=models.BooleanField(default=False, verbose_name='Notificación Enviada'),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('hijo', 'Hijo/a'), ('esposo', 'Esposo/a'), ('padre', 'Padre/Madre'), ('hermano', 'Hermano/a'), ('nieto', 'Nieto/a'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='telefono_familiar',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='ultima_notificacion',
            field=models.DateField(blank=True, null=True, verbose_name='Última Notificación'),
        ),
        migrations.AlterField(
            model_name='fallecido',
            name='maps',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
