# Generated by Django 4.2.7 on 2025-11-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0010_fallecido_email_familiar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallecido',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
