# Generated by Django 4.2.7 on 2025-11-05 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsimple', '0011_fallecido_segundo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallecido',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 5, 0, 28, 35, 208149, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
    ]
