# Generated by Django 4.2.7 on 2025-11-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudsimple", "0012_fallecido_fecha_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="fallecido",
            name="latitud",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=10,
                null=True,
                verbose_name="Latitud",
            ),
        ),
        migrations.AddField(
            model_name="fallecido",
            name="longitud",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="Longitud",
            ),
        ),
    ]
