# Generated by Django 4.2.7 on 2025-11-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudsimple", "0013_fallecido_latitud_fallecido_longitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="fallecido",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fotos_fallecidos/",
                verbose_name="Foto",
            ),
        ),
        migrations.AddField(
            model_name="fallecido",
            name="historia",
            field=models.TextField(blank=True, null=True, verbose_name="Historia"),
        ),
    ]
